### ISSUE TITLE
Error executing live-torrent in ubuntu16.04

### ISSUE THREAD

**Issue by sohag1426** [pldubouilh/live-torrent#17]
root@nginx-rtmp-hls:~# live-torrent -v -u https://live.computer/manifest.m3u8
/usr/local/lib/node_modules/live-torrent/cli.js:62
const makeManifest = async (cb) => {
                           ^

SyntaxError: Unexpected token (
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by pldubouilh** [comment]
Yep, the nodejs version shipped by default on xenial is an old version 4. `live-torrent` requires at least v8, check out either a PPA, or the docs on the nodejs website
